Bagian Awal belajar Tensorflow

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([
    [5,6],
    [6,2]
])

b = tf.constant([
    [3,1],
    [9,6]
])

mutval = tf.matmul(a,b)
concat_1 = tf.concat([a,b], axis=1)
concat_0 = tf.concat([a,b], axis=0)

print(f"""{mutval}, 
      
{concat_1}, 
      
{concat_0}""") # // print hasilnya

[[69 41]
 [36 18]], 
      
[[5 6 3 1]
 [6 2 9 6]], 
      
[[5 6]
 [6 2]
 [3 1]
 [9 6]]
